/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings/new` | `/bookings/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings/request` | `/bookings/request`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings/[id]` | `/bookings/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/browse/[id]` | `/browse/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/bookings` | `/bookings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/bookings/new` | `/bookings/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/bookings/request` | `/bookings/request`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/browse` | `/browse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/bookings/[id]` | `/bookings/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(main)'}/browse/[id]` | `/browse/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/bookings${`?${string}` | `#${string}` | ''}` | `/bookings${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/bookings/new${`?${string}` | `#${string}` | ''}` | `/bookings/new${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/bookings/request${`?${string}` | `#${string}` | ''}` | `/bookings/request${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/browse${`?${string}` | `#${string}` | ''}` | `/browse${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings` | `/bookings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings/new` | `/bookings/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/bookings/request` | `/bookings/request`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(main)'}/bookings/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/bookings/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/browse/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/browse/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/bookings/[id]` | `/bookings/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/browse/[id]` | `/browse/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
