/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/earnings` | `/earnings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/time/history` | `/time/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/time` | `/time`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/zones` | `/zones`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/schedule/[id]` | `/schedule/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/earnings` | `/earnings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/time/history` | `/time/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/time` | `/time`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/zones` | `/zones`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/schedule/[id]` | `/schedule/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/earnings${`?${string}` | `#${string}` | ''}` | `/earnings${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/time/history${`?${string}` | `#${string}` | ''}` | `/time/history${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/time${`?${string}` | `#${string}` | ''}` | `/time${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/zones${`?${string}` | `#${string}` | ''}` | `/zones${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/earnings` | `/earnings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/time/history` | `/time/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/time` | `/time`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/zones` | `/zones`; params?: Router.UnknownInputParams; } | `${'/(main)'}/schedule/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/schedule/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/schedule/[id]` | `/schedule/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
